language: python
python: "3.6"
cache: pip

install:
  - pip install -r requirements-test.txt -c constraints.txt codecov


jobs:
  include:
    - stage: test
      script: pytest --color=auto --cov=edp --cov-report=term-missing tests/
  allow_failures:
    - stage: lint
      script: mypy edp/
    - stage: lint
        script: pylint edp/


after_success:
  - codecov