language: python
python: "3.6"
cache: pip

env:
  - QT_QPA_PLATFORM=offscreen

stages:
  - test
  - lint

install:
  - pip install -r requirements-test.txt -c constraints.txt codecov

script:
  - pytest -svv --color=auto --cov=edp --cov-report=term-missing tests/
  - mypy edp/
  - pylint -j 0 --persistent=n edp/

after_success:
  - codecov
