language: python
python: "3.6"
cache: pip

install:
  - pip install -r requirements-test.txt -c constraints.txt

script:
  - pytest --color=auto --cov=edp --cov-report=term-missing tests/

after_success:
  - codecov