language: python
python: "3.6"
cache: pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt -c constraints.txt codecov

script:
  - pytest --color=auto --cov=edp --cov-report=term-missing tests/

after_success:
  - codecov