# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edp\gui\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 262)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_commander = QtWidgets.QLabel(self.centralwidget)
        self.label_commander.setObjectName("label_commander")
        self.horizontalLayout_3.addWidget(self.label_commander)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_system = QtWidgets.QLabel(self.centralwidget)
        self.label_system.setObjectName("label_system")
        self.horizontalLayout_2.addWidget(self.label_system)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_ship = QtWidgets.QLabel(self.centralwidget)
        self.label_ship.setObjectName("label_ship")
        self.horizontalLayout.addWidget(self.label_ship)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.list_widget_events = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget_events.setMinimumSize(QtCore.QSize(0, 100))
        self.list_widget_events.setMaximumSize(QtCore.QSize(16777215, 150))
        self.list_widget_events.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_widget_events.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list_widget_events.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_widget_events.setAutoScroll(False)
        self.list_widget_events.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_widget_events.setProperty("showDropIndicator", False)
        self.list_widget_events.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.list_widget_events.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.list_widget_events.setObjectName("list_widget_events")
        self.verticalLayout_2.addWidget(self.list_widget_events)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setTearOffEnabled(False)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOverview = QtWidgets.QAction(MainWindow)
        self.actionOverview.setCheckable(True)
        self.actionOverview.setChecked(True)
        self.actionOverview.setObjectName("actionOverview")
        self.actionEvent_list = QtWidgets.QAction(MainWindow)
        self.actionEvent_list.setCheckable(True)
        self.actionEvent_list.setChecked(True)
        self.actionEvent_list.setObjectName("actionEvent_list")
        self.menuView.addAction(self.actionOverview)
        self.menuView.addAction(self.actionEvent_list)
        self.menuView.addSeparator()
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDP"))
        self.label_5.setText(_translate("MainWindow", "Commander"))
        self.label_commander.setText(_translate("MainWindow", "Commander name"))
        self.label_3.setText(_translate("MainWindow", "System"))
        self.label_system.setText(_translate("MainWindow", "Sol"))
        self.label.setText(_translate("MainWindow", "Ship"))
        self.label_ship.setText(_translate("MainWindow", "TextLabel"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOverview.setText(_translate("MainWindow", "Overview"))
        self.actionEvent_list.setText(_translate("MainWindow", "Event list"))

