# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sashgorokhov\PycharmProjects\edp\edp\gui\ui\updater_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.version_label = QtWidgets.QLabel(Form)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout.addWidget(self.version_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.release_name_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.release_name_label.setFont(font)
        self.release_name_label.setTextFormat(QtCore.Qt.RichText)
        self.release_name_label.setWordWrap(True)
        self.release_name_label.setOpenExternalLinks(True)
        self.release_name_label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.release_name_label.setObjectName("release_name_label")
        self.verticalLayout.addWidget(self.release_name_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.release_version_label = QtWidgets.QLabel(Form)
        self.release_version_label.setObjectName("release_version_label")
        self.horizontalLayout_3.addWidget(self.release_version_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.skip_button = QtWidgets.QPushButton(Form)
        self.skip_button.setObjectName("skip_button")
        self.horizontalLayout_3.addWidget(self.skip_button)
        self.install_button = QtWidgets.QPushButton(Form)
        self.install_button.setObjectName("install_button")
        self.horizontalLayout_3.addWidget(self.install_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.download_progess_bar = QtWidgets.QProgressBar(Form)
        self.download_progess_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.download_progess_bar.setObjectName("download_progess_bar")
        self.verticalLayout.addWidget(self.download_progess_bar)
        self.install_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.install_label.setFont(font)
        self.install_label.setWordWrap(True)
        self.install_label.setObjectName("install_label")
        self.verticalLayout.addWidget(self.install_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "EDP - Updater"))
        self.label.setText(_translate("Form", "New version is available!"))
        self.label_2.setText(_translate("Form", "Your version:"))
        self.version_label.setText(_translate("Form", "v0.0.0"))
        self.release_name_label.setText(_translate("Form", "Release name"))
        self.label_3.setText(_translate("Form", "Version:"))
        self.release_version_label.setText(_translate("Form", "v0.0.0"))
        self.skip_button.setText(_translate("Form", "Skip"))
        self.install_button.setText(_translate("Form", "Install"))
        self.download_progess_bar.setFormat(_translate("Form", "%p%"))
        self.install_label.setText(_translate("Form", "Installing..."))

